export const coffeeShops = [
  {
    "name": "Rimbun Espresso & Brew Bar",
    "rating": 4.6,
    "reviewCount": 1400,
    "priceMin": 15000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. KIS. Mangunsarkoro, Jati Baru",
    "area": "Padang Timur",
    "hours": "07.00 - 21.00",
    "openHour": 7,
    "closeHour": 21,
    "tags": [
      "Wi-Fi",
      "Manual Brew",
      "Roastery",
      "Cozy",
      "Parkir"
    ],
    "photo": "https://assets.pikiran-rakyat.com/crop/0x0:0x0/1200x675/webp/photo/2024/10/12/3356828343.jpg",
    "description": "Salah satu coffee shop paling legendaris di Padang. Menyajikan kopi lokal Sumatera Barat seperti Kerinci dan Solok Radjo. Ada pilihan V60, pour-over, dan espresso. Juga tersedia menu makanan seperti roti bakar, sandwich, pasta, dan rice bowl dengan harga Rp15-50 ribu.",
    "mapsUrl": "https://maps.google.com/maps?q=Rimbun+Espresso+Padang",
    "instagram": "https://www.instagram.com/rimbuncoffee/"
  },
  {
    "name": "Pandora Coffee Nook",
    "rating": 4.9,
    "reviewCount": 129,
    "priceMin": 20000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Kamang No.17, Jati Baru",
    "area": "Padang Timur",
    "hours": "Buka 24 Jam",
    "openHour": 0,
    "closeHour": 24,
    "tags": [
      "24 Jam",
      "Live Acoustic",
      "Semi-Outdoor",
      "Instagramable"
    ],
    "photo": "https://itin-dev.wanderlogstatic.com/freeImage/Gv0Mr8CFGONkT4DICnko3XDZxtR4juF6",
    "description": "Rating tertinggi di Padang! Suasana cozy dengan pencahayaan temaram, tanaman di mana-mana, dan area duduk semi-outdoor. Sering ada live acoustic di akhir pekan. Menu kopi segar seperti iced black dengan hint citrus.",
    "mapsUrl": "https://maps.google.com/maps?q=Pandora+Coffee+Nook+Padang",
    "instagram": "https://www.instagram.com/pandoracoffeenook/"
  },
  {
    "name": "TOMORO COFFEE (Damar)",
    "rating": 4.8,
    "reviewCount": 375,
    "priceMin": 20000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Damar No.67 B/C",
    "area": "Padang Barat",
    "hours": "08.00 - 22.00",
    "openHour": 8,
    "closeHour": 22,
    "tags": [
      "Luas",
      "Matcha",
      "Cozy",
      "Wi-Fi"
    ],
    "photo": "https://media.giphy.com/avatars/tomorocoffeeph/vrk1vebjtrG8.png",
    "description": "Favorit warga Padang dengan rating 4.8. Menu matcha oat latte menjadi andalan pelanggan. Area yang luas dan nyaman mendukung berbagai aktivitas, mulai dari nongkrong hingga kerja remote.",
    "mapsUrl": "https://maps.google.com/maps?q=Tomoro+Coffee+Padang+Jl+Damar",
    "instagram": "https://www.instagram.com/tomorocoffee.id/"
  },
  {
    "name": "Pojok Steva",
    "rating": 4.8,
    "reviewCount": 73,
    "priceMin": 10000,
    "priceMax": 25000,
    "priceCategory": "budget",
    "location": "Jl. Jamal Jamil No.77, Surau Gadang",
    "area": "Nanggalo",
    "hours": "09.00 - 21.00",
    "openHour": 9,
    "closeHour": 21,
    "tags": [
      "Budget",
      "Baca Buku",
      "Santai",
      "Murah"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEusd9NaPVOHu-k-Ba8u2j2E2cueQudgOcfi7o1-S6V01WR3BPT-Tn6I4v0rew2QR3K9bCNG2vlPpdXbnjqBo30QyOd4dja0p3UECqWdlkqrDqi89yXdIcvIOiQ9X4xcUa-NufQ=s1360-w1360-h1020-rw",
    "description": "Konsep unik kedai kopi sekaligus sudut baca. Tempat yang menarik bagi pecinta buku dan kopi. Harga sangat terjangkau Rp1-25 ribu, cocok untuk mahasiswa.",
    "mapsUrl": "https://maps.google.com/maps?q=Pojok+Steva+Padang",
    "instagram": "https://www.instagram.com/pustakasteva/"
  },
  {
    "name": "Café Merjer",
    "rating": 4.7,
    "reviewCount": 587,
    "priceMin": 25000,
    "priceMax": 60000,
    "priceCategory": "mid",
    "location": "Jl. Ujung Gurun No.88A",
    "area": "Padang Barat",
    "hours": "09.00 - 22.00",
    "openHour": 9,
    "closeHour": 22,
    "tags": [
      "Single Origin",
      "Specialty",
      "Indoor"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGogTCIgmlNtgYz392MIFnwnXiIdAWztT2JZ26gymEsM6bmY1rbYvgNAvCrcU5wyLZx2Nqf_087kdrbHADqluo62EKNf3eSpWt3Z55ynpENc5ptec7yXwhVLtUhTjQTjEFNnwo=s1360-w1360-h1020-rw",
    "description": "Menawarkan ragam menu kopi dengan karakter rasa yang kuat dan cenderung asam - cocok untuk penikmat kopi single origin. Salah satu yang paling banyak diulas di Padang.",
    "mapsUrl": "https://maps.google.com/maps?q=Cafe+Merjer+Padang",
    "instagram": "https://www.instagram.com/cafemerjer/"
  },
  {
    "name": "Maison Merjer",
    "rating": 4.7,
    "reviewCount": 200,
    "priceMin": 30000,
    "priceMax": 65000,
    "priceCategory": "mid",
    "location": "Jl. Batang Naras No.2B",
    "area": "Padang Barat",
    "hours": "10.00 - 22.00",
    "openHour": 10,
    "closeHour": 22,
    "tags": [
      "Quiet",
      "WFH",
      "Nugas",
      "Wi-Fi"
    ],
    "photo": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR9ewOkpHgA2TlDAY-dGZC8oUX0e-ezhtgEnA&s",
    "description": "Banyak pengunjung merekomendasikan sebagai tempat bekerja atau menyelesaikan tugas karena suasananya yang tenang dan kondusif.",
    "mapsUrl": "https://maps.google.com/maps?q=Maison+Merjer+Padang",
    "instagram": "https://www.instagram.com/maisonmerjer/"
  },
  {
    "name": "Trimity",
    "rating": 4.7,
    "reviewCount": 138,
    "priceMin": 10000,
    "priceMax": 25000,
    "priceCategory": "budget",
    "location": "Gg. Nuri, Jl. Samudera No.9, Air Tawar Barat",
    "area": "Padang Utara",
    "hours": "08.00 - 23.00",
    "openHour": 8,
    "closeHour": 23,
    "tags": [
      "Budget",
      "Wi-Fi",
      "Mahasiswa",
      "Murah"
    ],
    "photo": "https://lh3.googleusercontent.com/p/AF1QipNyZ2hAinaUaQUGBWAHAxRm4GxLi_WT9sh43jRR=s1360-w1360-h1020-rw",
    "description": "Populer di kalangan mahasiswa. Harga sangat terjangkau, fasilitas Wi-Fi memadai untuk belajar maupun berkumpul. Berlokasi strategis dekat kawasan pantai Padang.",
    "mapsUrl": "https://maps.google.com/maps?q=Trimity+Coffee+Padang",
    "instagram": "https://www.instagram.com/trimity.id/"
  },
  {
    "name": "MASON Coffee",
    "rating": 4.6,
    "reviewCount": 332,
    "priceMin": 45000,
    "priceMax": 120000,
    "priceCategory": "premium",
    "location": "Jl. Hiligoo No.50, Belakang Padang",
    "area": "Padang Barat",
    "hours": "11.30 - 22.00",
    "openHour": 11,
    "closeHour": 22,
    "tags": [
      "Estetik",
      "Date",
      "Glamour",
      "Premium",
      "Instagramable"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFR0uC6e11W7CzQ6DPoC6yXCNQLKK309BszgOed1u3up_G2_uMhIR7k7CVWfh0xYvbKeflZ4vLlBuO6heMLSRJEXaiCMFzkYpH1K4lnVEEq9EM1PCZZ49H65IbUD78SBlwJiUP0=s1360-w1360-h1020-rw",
    "description": "Coffee shop dengan interior glamour dan estetik. Tata ruang rapi dan penyajian menarik. Cocok untuk first date atau gathering keluarga. Menu mulai dari tart hingga ribs. Harga cukup premium.",
    "mapsUrl": "https://maps.google.com/maps?q=Mason+Coffee+Padang",
    "instagram": "https://www.instagram.com/masoncoffee.pdg/"
  },
  {
    "name": "Kubik Koffie",
    "rating": 4.4,
    "reviewCount": 1100,
    "priceMin": 20000,
    "priceMax": 55000,
    "priceCategory": "mid",
    "location": "Jl. Olo Ladang No.12, Olo",
    "area": "Padang Barat",
    "hours": "09.00 - 22.00",
    "openHour": 9,
    "closeHour": 22,
    "tags": [
      "Indoor/Outdoor",
      "Meeting Room",
      "Wi-Fi",
      "Parkir",
      "Instagramable"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEHE0y6YFBlr1aYmx9B79nUnVDcu5EgLl6QZIhIbJH9QLlgv3srAsF66gX6pwUMj4ZC3h850QaV86NCQd2fi1Qe7gX56morR_thsSDH1R-0m8_4tkdS3bCTWMO5FdhZV-cx93ri2AyxyJc=s1360-w1360-h1020-rw",
    "description": "Menu tropical coffee menjadi ciri khas. Ada area indoor dan outdoor dengan banyak sudut foto instagramable. Tersedia ruang meeting yang bisa disewa. Harga ramah kantong dan parkir mudah.",
    "mapsUrl": "https://maps.google.com/maps?q=Kubik+Koffie+Padang",
    "instagram": "https://www.instagram.com/kubikkoffie/"
  },
  {
    "name": "Situ Koffie",
    "rating": 4.6,
    "reviewCount": 298,
    "priceMin": 18000,
    "priceMax": 40000,
    "priceCategory": "budget",
    "location": "Jl. Mawar No.10",
    "area": "Padang Utara",
    "hours": "09.00 - 22.00",
    "openHour": 9,
    "closeHour": 22,
    "tags": [
      "Kopi Susu",
      "Cozy",
      "Creamy"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHbGQ_q-k4WBkgYB8rQa8opL9RvUgDXSdi4_LXYCw4LIY6ulrfHt8OxIrU0Uz1ASowVe4S6Imy3Y-5-Ct5ms7af77AB_K53MyZ2gVdxCOZHfIq1hfP3T4lJws3a7NDHDN1DYmLGNdLITIwi=s1360-w1360-h1020-rw",
    "description": "Dikenal dengan racikan kopi susu yang creamy namun tetap ringan. Mudah dinikmati oleh berbagai kalangan, termasuk yang tidak terlalu suka kopi pahit.",
    "mapsUrl": "https://maps.google.com/maps?q=Situ+Koffie+Padang",
    "instagram": "https://www.instagram.com/situkoffie/"
  },
  {
    "name": "House Of Musi",
    "rating": 4.6,
    "reviewCount": 237,
    "priceMin": 20000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Musi No.35, Rimbo Kaluang",
    "area": "Padang Barat",
    "hours": "09.00 - 00.00",
    "openHour": 9,
    "closeHour": 24,
    "tags": [
      "Vintage",
      "Artistik",
      "Indoor/Outdoor",
      "Nugas"
    ],
    "photo": "https://itin-dev.wanderlogstatic.com/freeImage/QSdcBm4fIV0LQf4UCLAfs4zdSqnadqT5",
    "description": "Vibe vintage-smart yang edgy dengan bar kopi klasik dan kursi kayu. Nuansa indoor cozy dan outdoor yang adem. Cocok untuk nugas, ngopi santai, atau ngobrol sore dengan sentuhan artistik.",
    "mapsUrl": "https://maps.google.com/maps?q=House+of+Musi+Padang",
    "instagram": "https://www.instagram.com/houseof.musi/?hl=id"
  },
  {
    "name": "HOM.id Coffee and Pastry",
    "rating": 4.5,
    "reviewCount": 185,
    "priceMin": 25000,
    "priceMax": 55000,
    "priceCategory": "mid",
    "location": "Jl. Jambi Asratek No.2, Ulak Karang",
    "area": "Padang Utara",
    "hours": "08.00 - 22.00",
    "openHour": 8,
    "closeHour": 22,
    "tags": [
      "Pastry",
      "Cold Brew",
      "Homelike",
      "Instagramable"
    ],
    "photo": "https://westsumatra360.com/wp-content/uploads/2025/08/HOM-Cafe-1.webp",
    "description": "Homelike vibes dengan dekor minimalis, sentuhan kayu, dan tanaman hijau. Menu kopi variatif dari manual brew hingga cold brew rasa lychee dan green apple. Pilihan pastry seperti cheesecake dan waffle choco.",
    "mapsUrl": "https://maps.google.com/maps?q=HOM.id+Coffee+Padang",
    "instagram": "https://www.instagram.com/hom.padang/"
  },
  {
    "name": "Kupi Batigo",
    "rating": 4.5,
    "reviewCount": 310,
    "priceMin": 12000,
    "priceMax": 35000,
    "priceCategory": "budget",
    "location": "Jl. KH. Ahmad Dahlan No.19, Alai Parak Kopi",
    "area": "Padang Utara",
    "hours": "09.00 - 23.00",
    "openHour": 9,
    "closeHour": 23,
    "tags": [
      "Teh Talua",
      "Kopi Lokal",
      "Dekat Masjid Raya",
      "Minang"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEvO9IYNns9EGL2XqYIST8Zr6dtj7IQYyI30L93MkHEOR2yWfa_qH43tUsgOj_2d0W2A_h6GdB9mU3z4mXB52BQq44WkenKI_8QrxZa20ADX0h9_VQFuWDos5-Z4fQSaZBC_tLOPw=s1360-w1360-h1020-rw",
    "description": "Dekat Masjid Raya Sumatera Barat (sekitar 400 meter). Wajib coba minuman khas Sumatera Barat seperti Teh Talua dan kopi-kopi andalan mereka. Suasana sejuk dan nyaman.",
    "mapsUrl": "https://maps.google.com/maps?q=Kupi+Batigo+Padang",
    "instagram": "https://www.instagram.com/kupibatigo_padang/"
  },
  {
    "name": "Kamtumi Coffee",
    "rating": 4.4,
    "reviewCount": 420,
    "priceMin": 18000,
    "priceMax": 45000,
    "priceCategory": "budget",
    "location": "Jl. Ujung Gurun No.152, Ujung Gurun",
    "area": "Padang Barat",
    "hours": "08.00 - 00.00",
    "openHour": 8,
    "closeHour": 24,
    "tags": [
      "Industrial",
      "Vintage",
      "Indoor/Semi-Outdoor",
      "Luas"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAGqWjS4_O4eG-dheM2Gt3Me8ei0dxyPemesXS7W3bnEiLtgcfqsnXynluEb95qfdBbvHFAlC_TqqLI0MN6pCmfSql164BATsJD3SrdL5lhjiEcMjPeYCUH7GlZLRA15zVaS4xoeDsWPQET5=s1360-w1360-h1020-rw",
    "description": "Vibe industrial dengan dekor vintage yang keren. Area indoor dan semi-outdoor yang luas. Menu signature Es Kopi Krimi jadi favorit banyak pengunjung. Harga ramah di dompet.",
    "mapsUrl": "https://maps.google.com/maps?q=Kamtumi+Coffee+Padang",
    "instagram": "https://www.instagram.com/kamtumicoffee/?hl=id"
  },
  {
    "name": "Maloby Coffee and Space",
    "rating": 4.6,
    "reviewCount": 82,
    "priceMin": 20000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Situjuh No.18",
    "area": "Padang Timur",
    "hours": "09.00 - 22.00",
    "openHour": 9,
    "closeHour": 22,
    "tags": [
      "Cozy",
      "Brown Coffee",
      "Space"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFIasgF28BhJ1PUs4Uwrher4ir9G7fjq7hTUkBBAshGuELOfOgK7XeZs3fcg7TcVQURxI1a-8SpWQ4TnES8ihQiXZjMOrlni-mdoihLFm1FhTbgbJQ38kO9PkaihLyyBH1Eclsb=s1360-w1360-h1020-rw",
    "description": "Dikenal dengan brown coffee creamy yang bertekstur lembut dan rasa seimbang - cocok untuk penikmat kopi ringan. Suasana nyaman untuk nongkrong atau bekerja.",
    "mapsUrl": "https://maps.google.com/maps?q=Maloby+Coffee+Padang",
    "instagram": "https://www.instagram.com/malobycoffeeandspace/"
  },
  {
    "name": "TEDE COFFEE",
    "rating": 4.5,
    "reviewCount": 380,
    "priceMin": 20000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. S. Parman No.155 A, Ulak Karang Selatan",
    "area": "Padang Utara",
    "hours": "09.00 - 23.00",
    "openHour": 9,
    "closeHour": 23,
    "tags": [
      "Working Space",
      "Meeting Room",
      "3 Lantai",
      "Wi-Fi",
      "Mahasiswa"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHtqegvYDH3uFkopuBjHZQ9_GZDb899Q5gvdz6DaHBlulI5pdhyCX2J5NRJbxANHoikj-lciBv_RWzrMFS66TdB7Tvm0rxSeIAWzTwv5lazNFSW8Scw7KiDi-SLauYH9sG3h9BB=s1360-w1360-h1020-rw",
    "description": "Tempat nongkrong favorit pelajar dan mahasiswa dengan tiga lantai, banyak pilihan seating, working space, dan menu kopi khas seperti La Familia.",
    "mapsUrl": "https://maps.google.com/maps?q=TEDE+COFFEE+Padang",
    "instagram": "https://www.instagram.com/tede.coffee/"
  },
  {
    "name": "Menyala Coffee & Roastery",
    "rating": 4.4,
    "reviewCount": 316,
    "priceMin": 25000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Bandar Purus, Padang Pasir",
    "area": "Padang Barat",
    "hours": "08.00 - 22.00",
    "openHour": 8,
    "closeHour": 22,
    "tags": [
      "Roastery",
      "Manual Brew",
      "Live Music",
      "Outdoor",
      "Cozy"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH_133heypdl57Cy2_TSUzLhDUYbOpCNMwRQROjn0Z96UR0S2tqro2EW5m1IdJoeNGAtNLVe2C-BEyyUlwH5y3vsUAag4X8DiQ7Fgm7cq3gtGtdQfnTKJQhZd9pgnrzx-nFdZH4=s1360-w1360-h1020-rw",
    "description": "Spot ngopi yang dikenal dengan roasting yang serius, pilihan espresso-based drinks yang beragam, dan ambience nyaman untuk santai atau kerja.",
    "mapsUrl": "https://maps.google.com/maps?q=Menyala+Coffee+and+Roastery+Padang",
    "instagram": "https://www.instagram.com/menyala.coffee/"
  },
  {
    "name": "Coffeenary (Unand)",
    "rating": 4.6,
    "reviewCount": 60,
    "priceMin": 15000,
    "priceMax": 40000,
    "priceCategory": "mid",
    "location": "Kampus FEB Unand, Limau Manis",
    "area": "Pauh",
    "hours": "07.00 - 19.00",
    "openHour": 7,
    "closeHour": 19,
    "tags": [
      "Kampus",
      "View Hijau",
      "Wi-Fi",
      "Indoor/Outdoor",
      "Mahasiswa"
    ],
    "photo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Coffeenary_Caf%C3%A9_Padang.jpg",
    "description": "Coffee shop di kawasan FEB Universitas Andalas dengan suasana sejuk, area indoor dan outdoor, serta vibe kampus yang santai untuk belajar atau nongkrong.",
    "mapsUrl": "https://maps.google.com/maps?q=Coffeenary+Padang",
    "instagram": "",
    "secondaryUrl": "https://www.unand.ac.id/2025/1216-unand-resmikan-kedai-kopi-coffenary-kedua-di-kis-mangunsarkoro",
    "secondaryLabel": "Info Resmi"
  },
  {
    "name": "Starbucks Ahmad Yani Padang",
    "rating": 4.1,
    "reviewCount": 247,
    "priceMin": 22000,
    "priceMax": 55000,
    "priceCategory": "mid",
    "location": "Jl. Jend. A Yani No.8, Kampung Jao",
    "area": "Padang Barat",
    "hours": "07.00 - 22.00",
    "openHour": 7,
    "closeHour": 22,
    "tags": [
      "Chain Coffee",
      "Wi-Fi",
      "Kerja",
      "AC",
      "Pusat Kota"
    ],
    "photo": "https://commons.wikimedia.org/wiki/Special:Redirect/file/Starbucks_Ahmad_Yani_Padang.jpg",
    "description": "Gerai Starbucks pertama di Padang dengan bangunan sendiri, interior nyaman, dan cocok untuk meeting santai atau kerja sambil ngopi di pusat kota.",
    "mapsUrl": "https://maps.google.com/maps?q=Starbucks+Ahmad+Yani+Padang",
    "instagram": "https://linktr.ee/SbuxIDOfficialStores"
  },
  {
    "name": "Paliospiti",
    "rating": 4.6,
    "reviewCount": 140,
    "priceMin": 18000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Kamang, Jati Baru",
    "area": "Padang Timur",
    "hours": "Buka 24 Jam",
    "openHour": 0,
    "closeHour": 24,
    "tags": [
      "24 Jam",
      "Cozy",
      "Wi-Fi",
      "AC",
      "Parkir"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFCPA4zM0WygQhJqLieiz-UAD4mOhXgEbSmkkg8PlMVZcPhpYkGWvYLSHgK3QaoKyPQnsZnhZMTKR0m6HyLmSdqnWVhZ8IFdzUQl4kPfpvunpPbw0zsZ43Bvc8Hlirpc9CV8NJS=s1360-w1360-h1020-rw",
    "description": "Coffee shop favorit 24 jam dengan konsep rumahan yang hangat. Cocok untuk nongkrong panjang, nugas, atau meeting santai dengan fasilitas lengkap.",
    "mapsUrl": "https://maps.google.com/maps?q=Paliospiti+Padang",
    "instagram": "https://www.instagram.com/paliospiti/",
    "secondaryUrl": "https://westsumatra360.com/5-coffee-shops-yang-buka-24-jam-di-kota-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Toko Kopi Kita (Kopkit Jati)",
    "rating": 4.5,
    "reviewCount": 180,
    "priceMin": 15000,
    "priceMax": 40000,
    "priceCategory": "mid",
    "location": "Jl. Abdul Muis No.9b, Jati Baru",
    "area": "Padang Timur",
    "hours": "Buka 24 Jam",
    "openHour": 0,
    "closeHour": 24,
    "tags": [
      "24 Jam",
      "Cozy",
      "Wi-Fi",
      "Mushola",
      "Mahasiswa"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFpSZuMrCz2hBYqy603W5A18ghrvZNGQy_isdXJssAVk8DVUkobPLqBQQVhPXhgNw1Jl3MBx1ZiV0eF-auadWfnVS_DC_d103OKfJbC565wrXdSdN-RES6rlsg3XkE3NFvDqKA=s1360-w1360-h1020-rw",
    "description": "Tempat ngopi 24 jam yang hangat dan nyaman di kawasan Jati Baru. Menunya beragam dari kopi original sampai matcha dan varian literan.",
    "mapsUrl": "https://maps.google.com/maps?q=Toko+Kopi+Kita+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/5-coffee-shops-yang-buka-24-jam-di-kota-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Wabe (Warung Babe)",
    "rating": 4.6,
    "reviewCount": 120,
    "priceMin": 20000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Batang Arau No.88, Berok Nipah",
    "area": "Padang Selatan",
    "hours": "Buka 24 Jam",
    "openHour": 0,
    "closeHour": 24,
    "tags": [
      "24 Jam",
      "Photobooth",
      "Estetik",
      "Indoor/Outdoor",
      "Instagramable"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAE1YF1BRWJEOc6UvTUJQ8XfnQUvtNEe2VLvHxBE7tNzDVveVXACe1h5-t64P5JJmy84eAx-LrtJMwzwyhlSAyE05NTJyQ-gLtGAyuwxMCdeMhMO9rgxl_ph-Q6acoNPCBHVg_p5ow=s1360-w1360-h1020-rw",
    "description": "Cafe estetik dengan suasana luas dan banyak spot foto. Salah satu yang paling cocok untuk nongkrong santai, foto-foto, dan kumpul malam.",
    "mapsUrl": "https://maps.google.com/maps?q=Wabe+Warung+Babe+Padang",
    "instagram": "https://www.instagram.com/warungbabe/",
    "secondaryUrl": "https://westsumatra360.com/place-to-go-in-padang-7-rekomendasi-cafe-estetik-untuk-nongkrong-seru/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Showkoffie",
    "rating": 4.5,
    "reviewCount": 95,
    "priceMin": 18000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Veteran, Padang Pasir",
    "area": "Padang Barat",
    "hours": "16.00 - 23.00",
    "openHour": 16,
    "closeHour": 23,
    "tags": [
      "Live Music",
      "Semi-Outdoor",
      "Manual Brew",
      "Cozy",
      "Anak Muda"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAF1sRxeYAvwdTiNqDQ7Q4EVY6D5lrc6J_vwuohK_Za_PkefTc8xi8AuKd6ahGgD4bO7IgcoeejC0KErcEBetwzMRLuJtKGHyPlEkERFin5eZjP7nsFd61-waGc-WTHGHOwZvhJ7=s1360-w1360-h1020-rw",
    "description": "Tempat favorit anak muda Padang dengan konsep semi-outdoor dan live music harian. Nyaman untuk santai sore sampai malam sambil menikmati kopi signature.",
    "mapsUrl": "https://maps.google.com/maps?q=Showkoffie+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/cafe-dengan-live-musik-di-kota-padang-simak-5-rekomendasi-berikut/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Parewa Coffee (Bandar Purus)",
    "rating": 4.5,
    "reviewCount": 110,
    "priceMin": 15000,
    "priceMax": 40000,
    "priceCategory": "mid",
    "location": "Jl. Bandar Purus No.17, Padang Pasir",
    "area": "Padang Barat",
    "hours": "Buka 24 Jam",
    "openHour": 0,
    "closeHour": 24,
    "tags": [
      "24 Jam",
      "Indoor/Outdoor",
      "Murah",
      "Parkir",
      "Nongkrong"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG-kPquC4Xj5qTDnAgcl3p1516uflNbfSpByyCWzJlQ9ZVWug1oATaptVWD4gm99o3GFlxuCwlALkRH2hmE0shliOtJhEjm9hIZO6GF-gMYng5gdWAGdBKXdoN8ssrHKPF1iqGM=s1360-w1360-h1020-rw",
    "description": "Cafe simpel namun nyaman di pusat kota dengan area indoor dan outdoor. Populer untuk santai malam karena rasa kopi yang pas dan harga yang relatif ramah.",
    "mapsUrl": "https://maps.google.com/maps?q=Parewa+Coffee+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/cafe-dengan-live-musik-di-kota-padang-simak-5-rekomendasi-berikut/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Foresthree Coffee",
    "rating": 4.5,
    "reviewCount": 489,
    "priceMin": 20000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Blk. Olo No.52, Olo",
    "area": "Padang Barat",
    "hours": "09.00 - 23.00",
    "openHour": 9,
    "closeHour": 23,
    "tags": [
      "Dessert",
      "Wi-Fi",
      "Prayer Room",
      "TV",
      "Cozy"
    ],
    "photo": "https://itin-dev.wanderlogstatic.com/freeImage/7B18BM0jduW3Xtr9oCleEVJLRZ2KF0Fk",
    "description": "Coffee shop nyaman di kawasan Olo yang dikenal dengan pilihan dessert, fasilitas praktis, dan suasana santai untuk nongkrong maupun kerja ringan.",
    "mapsUrl": "https://maps.google.com/maps?q=Foresthree+Coffee+Padang",
    "instagram": "",
    "secondaryUrl": "https://wanderlog.com/place/details/16535252/foresthree-coffee",
    "secondaryLabel": "Ulasan"
  },
  {
    "name": "Voca Kopi Padang",
    "rating": 4.6,
    "reviewCount": 247,
    "priceMin": 20000,
    "priceMax": 55000,
    "priceCategory": "mid",
    "location": "Jl. Bandar Purus No.75, Padang Pasir",
    "area": "Padang Barat",
    "hours": "08.00 - 23.00",
    "openHour": 8,
    "closeHour": 23,
    "tags": [
      "Family Friendly",
      "Playground",
      "Mushalla",
      "Indoor",
      "Makanan Lengkap"
    ],
    "photo": "https://itin-dev.wanderlogstatic.com/freeImage/GmA1haV5NgBGDc9fKOWMwqGTw6WYsnO4",
    "description": "Cafe dua lantai yang family-friendly dengan area bermain kecil, parkir luas, dan menu makanan-minuman yang beragam. Cocok untuk nongkrong ramean atau makan santai.",
    "mapsUrl": "https://maps.google.com/maps?q=Voca+Kopi+Padang",
    "instagram": "",
    "secondaryUrl": "https://wanderlog.com/place/details/14309959/voca-kopi-padang",
    "secondaryLabel": "Ulasan"
  },
  {
    "name": "KOPIGO PADANG",
    "rating": 4.5,
    "reviewCount": 263,
    "priceMin": 18000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Sawahan Dalam No.41, Sawahan",
    "area": "Padang Timur",
    "hours": "Buka 24 Jam",
    "openHour": 0,
    "closeHour": 24,
    "tags": [
      "24 Jam",
      "Makanan Lengkap",
      "Cozy",
      "Old Town",
      "Nongkrong"
    ],
    "photo": "https://itin-dev.wanderlogstatic.com/freeImage/EkvO9YB9gnQMc1FQ2WhIS9HZBiX0D9k3",
    "description": "Spot 24 jam di kawasan kota lama yang dikenal dengan kopi enak, makanan lengkap, dan pelayanan yang bagus. Pas untuk cari tempat santai kapan saja.",
    "mapsUrl": "https://maps.google.com/maps?q=KOPIGO+PADANG",
    "instagram": "",
    "secondaryUrl": "https://wanderlog.com/place/details/15926971/kopigo-padang",
    "secondaryLabel": "Ulasan"
  },
  {
    "name": "QQ Coffee Shop",
    "rating": 4.7,
    "reviewCount": 36,
    "priceMin": 18000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Bunda No.13, Ulak Karang Utara",
    "area": "Padang Utara",
    "hours": "10.00 - 23.00",
    "openHour": 10,
    "closeHour": 23,
    "tags": [
      "Vintage",
      "Billiard",
      "Karaoke",
      "Homey",
      "Family Friendly"
    ],
    "photo": "https://itin-dev.wanderlogstatic.com/freeImage/MiPtJvhiYhPufYKHS8Mu8vasPps5hFZx",
    "description": "Cafe bergaya vintage dengan suasana homie, pilihan makanan rumahan, serta fasilitas billiard dan karaoke. Enak untuk kumpul teman atau keluarga.",
    "mapsUrl": "https://maps.google.com/maps?q=QQ+Coffee+Shop+Padang",
    "instagram": "",
    "secondaryUrl": "https://wanderlog.com/place/details/12465439/qq-coffee-shop",
    "secondaryLabel": "Ulasan"
  },
  {
    "name": "Pavilon Coffee",
    "rating": 4.5,
    "reviewCount": 156,
    "priceMin": 20000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Hang Tuah No.154 B, Olo",
    "area": "Padang Barat",
    "hours": "14.00 - 22.30",
    "openHour": 14,
    "closeHour": 22.5,
    "tags": [
      "Quiet",
      "Darts",
      "Indoor",
      "Pantai Dekat",
      "Manual Brew"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHh77FbjfL-ThaUKVbLT30GuZL7EM7UZAtCL0zspCmK0GD4v8PNYIM8lBU6xnSXSpsbxn1CoMROiqK5xbT8n0iR3za5Zhm1909IhfTZNp2_5XxU7Ia4X8HYhmY7HKDNbOcJizEXTg=s1360-w1360-h1020-rw",
    "description": "Tempat ngopi yang tenang dekat Pantai Padang, cocok untuk santai malam atau kerja ringan. Area indoor nyaman dan ada dart machine untuk hiburan tambahan.",
    "mapsUrl": "https://maps.google.com/maps?q=Pavilon+coffee+Padang",
    "instagram": "",
    "secondaryUrl": "https://wanderlog.com/place/details/2676935",
    "secondaryLabel": "Ulasan"
  },
  {
    "name": "Kedai Kopi Opa Mahmud",
    "rating": 4.5,
    "reviewCount": 225,
    "priceMin": 18000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Purus II No.5, Purus",
    "area": "Padang Barat",
    "hours": "12.00 - 00.00",
    "openHour": 12,
    "closeHour": 24,
    "tags": [
      "Hidden Gem",
      "Pasta",
      "Hazelnut Coffee",
      "Music",
      "Nongkrong"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEK1lqlBh0UQqo7X4xAzQMmqs8JA9TcBoKktlMZszBKhABaJfd_2DcmeeJYgIFqg_2eW-Xuc5LfEs6t5NZ00It0EdiPHOBnrozcRtAcVGbLCNflAJEVG0aA-dVZxDUS6vCvB2U2=s1360-w1360-h1020-rw",
    "description": "Hidden gem di kawasan Purus dengan suasana ramai yang khas, kopi yang enak, dan menu pasta yang sering disebut pengunjung sebagai salah satu andalan.",
    "mapsUrl": "https://maps.google.com/maps?q=Kedai+Kopi+Opa+Mahmud+Padang",
    "instagram": "",
    "secondaryUrl": "https://wanderlog.com/place/details/10838989/kedai-kopi-opa-mahmud",
    "secondaryLabel": "Ulasan"
  },
  {
    "name": "Salejourn Cafe and Space",
    "rating": 4.3,
    "reviewCount": 232,
    "priceMin": 25000,
    "priceMax": 55000,
    "priceCategory": "mid",
    "location": "Jl. Ujung Gurun, Ujung Gurun",
    "area": "Padang Barat",
    "hours": "09.00 - 23.00",
    "openHour": 9,
    "closeHour": 23,
    "tags": [
      "Cafe Baru",
      "Cozy",
      "Photobooth",
      "WFC",
      "Instagramable"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAEBC2DjgGDknJeXQt6wUNL2tVSrWSnmkGsfLYRd8DLsmDGTLqb03tOktVaQcaqRC4sWqnB0UVJCtOxCErjXo9d3HX6xStjc0Nyl8A4vni5LoXIvJjVPxYq9LBdYi6mjykl9gg=s1360-w1360-h1020-rw",
    "description": "Cafe yang lagi naik di Padang Barat dengan interior minimalis modern, area duduk luas, dan suasana yang nyaman buat kerja, meeting santai, atau nongkrong lama sambil foto-foto.",
    "mapsUrl": "https://maps.google.com/maps?q=Salejourn+Cafe+and+Space+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/5-tempat-nongkrong-paling-instagramable-di-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Hanghouse Cafe",
    "rating": 4.6,
    "reviewCount": 95,
    "priceMin": 23000,
    "priceMax": 45000,
    "priceCategory": "mid",
    "location": "Jl. Hang Tuah No.207, Belakang Tangsi",
    "area": "Padang Barat",
    "hours": "10.00 - 02.00",
    "openHour": 10,
    "closeHour": 2,
    "tags": [
      "WFC",
      "Estetik",
      "Pantai Dekat",
      "Nugas",
      "Cozy"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHFTcrogf9T5RdwXNaT8kHtTv4SGhYqSSlje21Fc_KxawgkUikent9-Ji7WFZltC8T3n5SyMc_is8tJZR_YIsid3bDaoYgWk-wNPU774FS97VUIPbRILaSUzsrJFuoCq77I-_bd=s1360-w1360-h1020-rw",
    "description": "Cafe nyaman dekat Pantai Padang dengan suasana estetik dan menu variatif. Cocok untuk kerja dari cafe, nongkrong santai, atau healing sebentar dari rutinitas.",
    "mapsUrl": "https://maps.google.com/maps?q=Hanghouse+Cafe+Padang",
    "instagram": "https://www.instagram.com/hanghouse.pdg/",
    "secondaryUrl": "https://westsumatra360.com/hanghouse-cafe-tempat-nongkrong-nyaman-dekat-pantai-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Jiwani Coffee",
    "rating": 4.8,
    "reviewCount": 182,
    "priceMin": 18000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Belakang Olo 1 No.20, Kp. Jao",
    "area": "Padang Barat",
    "hours": "08.00 - 21.00",
    "openHour": 8,
    "closeHour": 21,
    "tags": [
      "Workspace",
      "Tenang",
      "Meeting",
      "Musholla",
      "Specialty Coffee"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAFaxGIcvMRK4lEHEBh_GIY10dFkpeodwq9ZCvIBqSpPavhIAChGT8OwAAP4Gwd8bJylG0qo9lD_IQJvvGI3kh_GvOOPc46XhCWE7aPuuDkEbjHmjr0LPByPnLAytDVtGD8ESlFI=s1360-w1360-h1020-rw",
    "description": "Coffee shop yang terkenal nyaman untuk kerja dan nugas, dengan area duduk yang mendukung fokus, suasana relatif tenang, serta pilihan kopi dan non-kopi yang sama-sama kuat.",
    "mapsUrl": "https://maps.google.com/maps?q=Jiwani+Coffee+Padang",
    "instagram": "https://www.instagram.com/jiwanicoffee/",
    "secondaryUrl": "https://westsumatra360.com/6-cafe-dengan-workspace-super-nyaman-di-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Eightea Coffee",
    "rating": 4.7,
    "reviewCount": 120,
    "priceMin": 22000,
    "priceMax": 55000,
    "priceCategory": "mid",
    "location": "Jl. Aur No.12, Padang Pasir",
    "area": "Padang Barat",
    "hours": "10.00 - 22.00",
    "openHour": 10,
    "closeHour": 22,
    "tags": [
      "Tea House",
      "Minimalis",
      "Nugas",
      "Wi-Fi",
      "Industrial"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAH9GYalfCeJqUJbIw1ipnbO5eXnmCw5yC0N7okiK8Fa-ja4M0WU_ULdGLCI1jCndTgVgHsvy_bT-EappEu4nqpZt1PHJa5_XPMAPWYAAnlyhMuNCtL_nRgK2wSKrdzBI6v0are_=s1360-w1360-h1020-rw",
    "description": "Spot simpel dan adem untuk kerja ringan atau hangout santai. Selain kopi, tempat ini juga dikenal dengan pilihan teh yang kuat dan plating makanan yang rapi.",
    "mapsUrl": "https://maps.google.com/maps?q=Eightea+Coffee+Padang",
    "instagram": "https://www.instagram.com/eighteaspace/",
    "secondaryUrl": "https://westsumatra360.com/7-cafe-industrial-di-padang-cozy-estetik-dan-produktif/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Menes Coffee & Eatery",
    "rating": 4.6,
    "reviewCount": 140,
    "priceMin": 20000,
    "priceMax": 55000,
    "priceCategory": "mid",
    "location": "Jl. Kartini No.24, Padang Pasir",
    "area": "Padang Barat",
    "hours": "08.00 - 04.00",
    "openHour": 8,
    "closeHour": 4,
    "tags": [
      "Cafe Baru",
      "Japanese Vibe",
      "Late Night",
      "Wi-Fi",
      "Instagramable"
    ],
    "photo": "https://westsumatra360.com/wp-content/uploads/2025/06/Menes-Coffee-768x812.jpg",
    "description": "Cafe yang cukup populer belakangan dengan nuansa ala Jepang modern, signature coffee yang kuat, dan jam operasional panjang untuk nongkrong sampai larut.",
    "mapsUrl": "https://maps.google.com/maps?q=Menes+Coffee+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/5-tempat-nongkrong-paling-instagramable-di-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Ortie Coffee",
    "rating": 4.7,
    "reviewCount": 95,
    "priceMin": 22000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Ujung Gurun No.19, Ujung Gurun",
    "area": "Padang Barat",
    "hours": "09.00 - 01.00",
    "openHour": 9,
    "closeHour": 1,
    "tags": [
      "Hidden Gem",
      "Matcha",
      "Cozy",
      "Nugas",
      "Cafe Baru"
    ],
    "photo": "https://lh3.googleusercontent.com/p/AF1QipN0PTiEq2kt6wN-Zl4xgxqPRPCh6Vsfp71LeS3O=s1360-w1360-h1020-rw",
    "description": "Hidden gem yang cocok untuk kerja, belajar, atau santai lama. Vibes-nya tenang, tempat duduk nyaman, dan menu signature coffee serta matcha-nya sering direkomendasikan.",
    "mapsUrl": "https://maps.google.com/maps?q=Ortie+Coffee+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/5-tempat-nongkrong-paling-instagramable-di-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Asira Coffee",
    "rating": 4.8,
    "reviewCount": 145,
    "priceMin": 18000,
    "priceMax": 50000,
    "priceCategory": "mid",
    "location": "Jl. Palembang No.14, Ulak Karang Selatan",
    "area": "Padang Utara",
    "hours": "09.00 - 23.00",
    "openHour": 9,
    "closeHour": 23,
    "tags": [
      "Award-Winning",
      "Colokan Banyak",
      "Study Spot",
      "Tenang",
      "Wi-Fi"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHZPFV7a3qe6phHKIzX1pzuKsAFdIbUaJQFqJiVjN1VftFgeydhtebTzhi9zUljvLMWfPjEltpTuRBiHsjSks92nQ6dcYnuMDuHNaTXzt98TAlcUUoGMDyJKtApw3kS20iyGWG7vl7MAXjQ=s1360-w1360-h1020-rw",
    "description": "Coffee shop yang kuat untuk kebutuhan kerja dan belajar karena tiap meja dikenal punya akses colokan yang memadai, suasananya tenang, dan kopi racikannya juga dihargai bagus.",
    "mapsUrl": "https://maps.google.com/maps?q=Asira+Coffee+Padang",
    "instagram": "https://www.instagram.com/asiracoffee/",
    "secondaryUrl": "https://wanderlog.com/place/details/16296750/asira-coffee",
    "secondaryLabel": "Ulasan"
  },
  {
    "name": "Kaldu",
    "rating": 4.1,
    "reviewCount": 259,
    "priceMin": 25000,
    "priceMax": 70000,
    "priceCategory": "premium",
    "location": "Jl. Raya Ampang No.24, Ampang",
    "area": "Kuranji",
    "hours": "10.00 - 21.45",
    "openHour": 10,
    "closeHour": 21.75,
    "tags": [
      "Cafe Baru",
      "Viral",
      "Dessert",
      "Family Friendly",
      "Instagramable"
    ],
    "photo": "https://westsumatra360.com/wp-content/uploads/2025/03/Kaldu-Official-300x199.jpg",
    "description": "Tempat nongkrong yang sering viral dengan interior yang rapi, banyak pilihan dessert dan makanan berat, serta cocok untuk keluarga, pasangan, atau hangout santai yang lebih estetik.",
    "mapsUrl": "https://maps.google.com/maps?q=Kaldu+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/5-tempat-nongkrong-paling-instagramable-di-padang/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Gruun Cafe",
    "rating": 4.5,
    "reviewCount": 90,
    "priceMin": 25000,
    "priceMax": 65000,
    "priceCategory": "premium",
    "location": "Jl. Pulau Karam No.135A, Kampung Pondok",
    "area": "Padang Barat",
    "hours": "10.00 - 20.00 / 21.00",
    "openHour": 10,
    "closeHour": 20,
    "tags": [
      "Healthy Cafe",
      "Minimalis",
      "WFC",
      "Matcha",
      "Cafe Baru"
    ],
    "photo": "https://lh3.googleusercontent.com/p/AF1QipMbcdyJRmknWyLxOTFWu4ATmbd9-mkEJDEgw8qx=s1360-w1360-h1020-rw",
    "description": "Cafe baru bernuansa sehat dengan interior minimalis dan suasana tenang. Cocok untuk yang cari tempat nongkrong sambil kerja, tapi tetap ingin pilihan menu yang lebih light dan fresh.",
    "mapsUrl": "https://maps.google.com/maps?q=Gruun+Cafe+Padang",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/5-rekomendasi-cafe-baru-di-padang-cocok-buat-healing-ngopi-atau-nugas/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "Smokehouse Resto",
    "rating": 4.5,
    "reviewCount": 85,
    "priceMin": 20000,
    "priceMax": 65000,
    "priceCategory": "premium",
    "location": "Jl. Batang Anai No.2, Rimbo Kaluang",
    "area": "Padang Barat",
    "hours": "10.00 - 22.00",
    "openHour": 10,
    "closeHour": 22,
    "tags": [
      "Cafe Baru",
      "European Vibe",
      "Rooftop",
      "Meeting",
      "Semi-Formal"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAHebD02QZUMJq8PHVvEG2ep4EOuFdW-FNzZo1h2ocYRRv9zn2rKWR9yXksgJwqUmvfLPCKaM5d8p5Y_p9YNl_xiFbY0XtOmPwxvIZPkYpkfcHn_VaRCRCzc_TE3FNjHoHTa4iE0Dpbicz8p=s1360-w1360-h1020-rw",
    "description": "Pilihan baru dengan vibe klasik Eropa, cocok untuk hangout yang lebih rapi, meeting semi-formal, atau dinner santai sambil ngopi dan menikmati area rooftop.",
    "mapsUrl": "https://lh3.googleusercontent.com/p/AF1QipOipk6Q9tfmzVOgId2ydMmlnhXqR2ZGLCYOKjtU=s1360-w1360-h1020-rw",
    "instagram": "",
    "secondaryUrl": "https://westsumatra360.com/5-rekomendasi-cafe-baru-di-padang-cocok-buat-healing-ngopi-atau-nugas/",
    "secondaryLabel": "Artikel"
  },
  {
    "name": "KiosK",
    "rating": 4.6,
    "reviewCount": 2127,
    "priceMin": 25000,
    "priceMax": 70000,
    "priceCategory": "premium",
    "location": "Jl. Tepi Pasang No.40-46, Kampung Pondok",
    "area": "Padang Barat",
    "hours": "11.00 - 22.00",
    "openHour": 11,
    "closeHour": 22,
    "tags": [
      "All-in-One",
      "Dessert",
      "Avocado Coffee",
      "Family",
      "City Hangout"
    ],
    "photo": "https://lh3.googleusercontent.com/gps-cs-s/APNQkAG5ZpfTX2mEebbFGkbMCfATstUCcftJxL4Q_6voNrbsabcZnzU3M3dkGlpQG_2G-OOL7Ku7J84y8uIWyEoQ4ldupX1IZokv-tCH7Cj8Z11H3PfJ05PdOUsj8zfDGE7pFM7YD6D4eDdhKwfe=s1360-w1360-h1020-rw",
    "description": "Tempat makan dan ngopi yang ramai dengan menu sangat luas, dari kopi sampai dessert dan makanan berat. Pas untuk yang cari spot all-in-one di area kota lama Padang.",
    "mapsUrl": "https://maps.google.com/maps?q=KiosK+Padang",
    "instagram": "",
    "secondaryUrl": "https://wanderlog.com/place/details/2676930/kiosk",
    "secondaryLabel": "Ulasan"
  }
];


